/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels_frames;

import exa2pro.Exa2Pro;
import exa2pro.xml_rules.XmlReadANDWrite;
import exa2pro.xml_rules.IcodelintRrules;
import exa2pro.xml_rules.Rule;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Nikos
 */
public class HomeJPanelRuleEffort extends javax.swing.JPanel {

    private List<HomeJPanelRule> allPanelRules= new ArrayList<>();
    private IcodelintRrules que;
    private HomeFrame homeFrame;
    
    /**
     * Creates new form HomeJPanelRuleEffort
     */
    public HomeJPanelRuleEffort(HomeFrame homeFrame) {
        this.homeFrame=homeFrame;
        initComponents();
        
        ButtonGroup groupRadio= new ButtonGroup();
        groupRadio.add(jRadioButtonF90);
        groupRadio.add(jRadioButtonF77);
        addActionListenersRadio();
        
        addAllRules("f90");
    }
    
    /**
    * Reads Xml and add all rules to Panel
    * @param version the version of Fortran f90 or f77
    */
    private void addAllRules(String version){
        try {
            que = XmlReadANDWrite.readRules(version);
            
            allPanelRules.clear();
            jPanelAllRules.removeAll();
            que.getRule().forEach((r) -> {
                HomeJPanelRule temp= new HomeJPanelRule(r);
                allPanelRules.add(temp);
                jPanelAllRules.add(temp);
            });
            jPanelAllRules.repaint();
            jPanelAllRules.revalidate();
        } catch (JAXBException ex) {
            Logger.getLogger(HomeJPanelRuleEffort.class.getName()).log(Level.SEVERE, null, ex);
            homeFrame.changeParentPanelSettings();
        }
    }
    
    /**
     * Adds Listeners to change the appeared Rules
     */
    private void addActionListenersRadio(){
        jRadioButtonF90.addActionListener((ActionEvent e) ->{
            addAllRules("f90");
        });
        jRadioButtonF77.addActionListener((ActionEvent e) ->{
            addAllRules("f77");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jPanelAllRules = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jRadioButtonF90 = new javax.swing.JRadioButton();
        jRadioButtonF77 = new javax.swing.JRadioButton();

        jPanelAllRules.setLayout(new java.awt.GridLayout(0, 2));
        jScrollPane8.setViewportView(jPanelAllRules);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jRadioButtonF90.setSelected(true);
        jRadioButtonF90.setText("Fortran 90");

        jRadioButtonF77.setText("Fortran 77");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonF90)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonF77)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane8)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 263, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonF90)
                    .addComponent(jRadioButtonF77))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        for(HomeJPanelRule temp: allPanelRules){
            for(int i=0; i<que.getRule().size(); i++){
                if(temp.getDescription().equals(que.getRule().get(i).getDescription())){
                    que.getRule().get(i).setRemediationFunctionBaseEffort(temp.getMinutes());
                    break;
                }
            }
        }
        try {
            //write file with new rule times
            File file;
            if(jRadioButtonF90.isSelected())
                file = new File("sonar-icode-cnes-plugin-1.3.0/src/main/resources/rules/icode-f90-rules.xml");
            else
                file = new File("sonar-icode-cnes-plugin-1.3.0/src/main/resources/rules/icode-f77-rules.xml");
            XmlReadANDWrite.writeRules(que, file);
            
            //build with maven the jar file
            String folder =(new File("sonar-icode-cnes-plugin-1.3.0/").getAbsolutePath());
            if(Exa2Pro.isWindows()){
                Process proc = Runtime.getRuntime().exec("cmd /c \"cd " + folder + " && "
                        + "mvn -Dmaven.test.skip=true package" + "\"");
                proc.waitFor();
            }
            else{
                
            }
            
            //copy new plugin to SonarQube
            Files.copy((new File("sonar-icode-cnes-plugin-1.3.0/target/sonaricode-1.3.0.jar")).toPath(),
                        (new File(Exa2Pro.sonarPath.replace("\\","/")+"/extensions/plugins/sonaricode-1.3.0.jar")).toPath(),
                        StandardCopyOption.REPLACE_EXISTING);
            
            //toDo
            //restart sonarQube
            
            homeFrame.changeParentPanelSettings();
        } catch (JAXBException | IOException | InterruptedException ex) {
            Logger.getLogger(HomeJPanelRuleEffort.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        homeFrame.changeParentPanelSettings();
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JPanel jPanelAllRules;
    private javax.swing.JRadioButton jRadioButtonF77;
    private javax.swing.JRadioButton jRadioButtonF90;
    private javax.swing.JScrollPane jScrollPane8;
    // End of variables declaration//GEN-END:variables

}
