/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels_frames;

import exa2pro.Project;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nikos
 */
public class JPanelAdmit extends javax.swing.JPanel {

    Project project;
    private List<PanelAdmitModelValueInput> modelsPanels= new ArrayList<>();
    
    /**
     * Creates new form JPanelAdmit
     */
    public JPanelAdmit(Project project) {
        this.project = project;
        initComponents();
        
        //toDO
        //populate decisions table
        
        jPanelNewDecision.setVisible(false);
        jPanelModels.setVisible(false);
        jPanelCreateCustom.setVisible(false);
        jPanelProvideV.setVisible(false);
        jPanelResults.setVisible(false);
        
        //costomizations
        jTableResultCostModel.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableResultCostModel.getColumnModel().getColumn(1).setMaxWidth(70);
        jTableResultBenefitModel.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTableResultBenefitModel.getColumnModel().getColumn(1).setMaxWidth(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableModels = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDecisions = new javax.swing.JTable();
        jButtonNewDecision = new javax.swing.JButton();
        jButtonAddCost = new javax.swing.JButton();
        jButtonAddBenefit = new javax.swing.JButton();
        jButtonAnalysis = new javax.swing.JButton();
        jPanelNewDecision = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextOwner = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonCreateDecision = new javax.swing.JButton();
        jPanelModels = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAllModels = new javax.swing.JTable();
        jButtonCreateModel = new javax.swing.JButton();
        jPanelCreateCustom = new javax.swing.JPanel();
        jButtonCreateCustomModel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCustomType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCustomName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxCustomEquation = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldVar = new javax.swing.JTextField();
        jButtonCustomParamAdd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxSymbol = new javax.swing.JComboBox<>();
        jButtonCustomSymbAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelProvideV = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButtonAnalyze = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanelModelsInputs = new javax.swing.JPanel();
        jPanelResults = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableResultCostModel = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableResultBenefitModel = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        jLabelTotalBenefits = new javax.swing.JLabel();
        jLabelTotalCosts = new javax.swing.JLabel();
        jLabelProfitLoss = new javax.swing.JLabel();
        jComboBoxParameters = new javax.swing.JComboBox<>();
        jTextFieldMinV = new javax.swing.JTextField();
        jTextFieldMaxV = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButtonTune = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableTotalBC = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jTableModels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Name", "Equation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableModels);

        jTableDecisions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Owner", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDecisions.setToolTipText("");
        jScrollPane1.setViewportView(jTableDecisions);

        jButtonNewDecision.setText("Create New Decision");
        jButtonNewDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewDecisionActionPerformed(evt);
            }
        });

        jButtonAddCost.setText("Add Cost Model");
        jButtonAddCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCostActionPerformed(evt);
            }
        });

        jButtonAddBenefit.setText("Add Benefit Model");
        jButtonAddBenefit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBenefitActionPerformed(evt);
            }
        });

        jButtonAnalysis.setText("Perform Analysis");
        jButtonAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddBenefit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnalysis))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNewDecision)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNewDecision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddCost)
                    .addComponent(jButtonAddBenefit)
                    .addComponent(jButtonAnalysis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1);

        jLabel2.setText("Name of Decision");

        jLabel3.setText("Owner");

        jLabel4.setText("Date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Create Decision");

        jButtonCreateDecision.setText("Create");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCreateDecision))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextName)
                            .addComponent(jTextOwner)
                            .addComponent(jTextDate))))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButtonCreateDecision)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelNewDecisionLayout = new javax.swing.GroupLayout(jPanelNewDecision);
        jPanelNewDecision.setLayout(jPanelNewDecisionLayout);
        jPanelNewDecisionLayout.setHorizontalGroup(
            jPanelNewDecisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewDecisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNewDecisionLayout.setVerticalGroup(
            jPanelNewDecisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewDecisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        add(jPanelNewDecision);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Select an existing model, or add a custom one");

        jTableAllModels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Name", "Equation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableAllModels);

        jButtonCreateModel.setText("Create Custom Model");
        jButtonCreateModel.setToolTipText("");
        jButtonCreateModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateModelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModelsLayout = new javax.swing.GroupLayout(jPanelModels);
        jPanelModels.setLayout(jPanelModelsLayout);
        jPanelModelsLayout.setHorizontalGroup(
            jPanelModelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelModelsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelModelsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCreateModel)))
                .addContainerGap())
        );
        jPanelModelsLayout.setVerticalGroup(
            jPanelModelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModelsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreateModel)
                .addContainerGap())
        );

        add(jPanelModels);

        jButtonCreateCustomModel.setText("Create");
        jButtonCreateCustomModel.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Create a Custom Model");

        jLabel7.setText(" Type:");

        jComboBoxCustomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cost", "Benefit" }));

        jLabel8.setText("Model Name");

        jLabel9.setText("Type of Equation");

        jComboBoxCustomEquation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linear", "Product" }));

        jLabel10.setText("Equation builder:");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonCustomParamAdd.setText("Add");
        jButtonCustomParamAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomParamAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldVar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonCustomParamAdd)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomParamAdd))
                .addGap(3, 3, 3))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxSymbol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/", "(", ")" }));

        jButtonCustomSymbAdd.setText("Add");
        jButtonCustomSymbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomSymbAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCustomSymbAdd)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCustomSymbAdd))
                .addGap(3, 3, 3))
        );

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelCreateCustomLayout = new javax.swing.GroupLayout(jPanelCreateCustom);
        jPanelCreateCustom.setLayout(jPanelCreateCustomLayout);
        jPanelCreateCustomLayout.setHorizontalGroup(
            jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateCustomLayout.createSequentialGroup()
                .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCreateCustomLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCreateCustomLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonDelete)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCreateCustomModel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCreateCustomLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCustomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCreateCustomLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCreateCustomLayout.createSequentialGroup()
                                .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelCreateCustomLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCustomName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxCustomEquation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelCreateCustomLayout.setVerticalGroup(
            jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCreateCustomLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxCustomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldCustomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxCustomEquation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanelCreateCustomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCreateCustomModel)
                    .addComponent(jButtonDelete))
                .addContainerGap())
        );

        add(jPanelCreateCustom);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Provide the values for the models' parameters");

        jButtonAnalyze.setText("Analyze!");
        jButtonAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalyzeActionPerformed(evt);
            }
        });

        jPanelModelsInputs.setLayout(new java.awt.GridLayout(0, 2));
        jScrollPane8.setViewportView(jPanelModelsInputs);

        javax.swing.GroupLayout jPanelProvideVLayout = new javax.swing.GroupLayout(jPanelProvideV);
        jPanelProvideV.setLayout(jPanelProvideVLayout);
        jPanelProvideVLayout.setHorizontalGroup(
            jPanelProvideVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProvideVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProvideVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanelProvideVLayout.createSequentialGroup()
                        .addGroup(jPanelProvideVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jButtonAnalyze))
                        .addGap(0, 359, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProvideVLayout.setVerticalGroup(
            jPanelProvideVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProvideVLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnalyze)
                .addContainerGap())
        );

        add(jPanelProvideV);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setText("Provide the values for the models' parameters");

        jTableResultCostModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cost Model", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableResultCostModel);

        jTableResultBenefitModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Benefit Model", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableResultBenefitModel);

        jLabel45.setText("Select Parameter to Tune the Model:");

        jLabelTotalBenefits.setText("Total Benefits: 0.00$");

        jLabelTotalCosts.setText("Total Costs: -0.00$");

        jLabelProfitLoss.setText("Profit/Loss: 0.00$");

        jComboBoxParameters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Customer Support Hourly Rate", "Hours saved while performing Customers Support", "Expected Increase", "Market Share", "Market Size", "Price", "Customers that Upgraded", "Upgrade Cost", "Cost per LoC", "Lines of Code to be transferred", "CC Increase", "LoC Increase", "LoC updated evry year", "Percentage classes updated every year", "Instructor Hourly Rate", "Training Sessions in Hours" }));

        jTextFieldMinV.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMinV.setText("0");

        jTextFieldMaxV.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMaxV.setText("0");

        jLabel37.setText("Min value");

        jLabel38.setText("Max value");

        jButtonTune.setText("Tune Model");

        jTableTotalBC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {"", null, null, null},
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Total Benefit", "Total Cost", "Profit/Loss"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableTotalBC);

        javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addGroup(jPanelResultsLayout.createSequentialGroup()
                        .addComponent(jLabelTotalBenefits)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelTotalCosts)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelProfitLoss))
                    .addGroup(jPanelResultsLayout.createSequentialGroup()
                        .addComponent(jComboBoxParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMinV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaxV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTune))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelResultsLayout.createSequentialGroup()
                        .addGroup(jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalBenefits)
                    .addComponent(jLabelTotalCosts)
                    .addComponent(jLabelProfitLoss))
                .addGap(18, 18, 18)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jTextFieldMinV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(jTextFieldMaxV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTune))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        add(jPanelResults);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewDecisionActionPerformed
        jPanelNewDecision.setVisible(true);
        jPanelModels.setVisible(false);
        jPanelCreateCustom.setVisible(false);
        jPanelProvideV.setVisible(false);
        jPanelResults.setVisible(false);
    }//GEN-LAST:event_jButtonNewDecisionActionPerformed

    private void jButtonAddCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCostActionPerformed
        jPanelNewDecision.setVisible(false);
        jPanelModels.setVisible(true);
        jPanelCreateCustom.setVisible(false);
        jPanelProvideV.setVisible(false);
        jPanelResults.setVisible(false);
        
        //toDo
        //populate table with cost models
    }//GEN-LAST:event_jButtonAddCostActionPerformed

    private void jButtonAddBenefitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBenefitActionPerformed
        jPanelNewDecision.setVisible(false);
        jPanelModels.setVisible(true);
        jPanelCreateCustom.setVisible(false);
        jPanelProvideV.setVisible(false);
        jPanelResults.setVisible(false);
        
        //toDo
        //populate table with benefit models
    }//GEN-LAST:event_jButtonAddBenefitActionPerformed

    private void jButtonAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalysisActionPerformed
        jPanelNewDecision.setVisible(false);
        jPanelModels.setVisible(false);
        jPanelCreateCustom.setVisible(false);
        jPanelProvideV.setVisible(true);
        jPanelResults.setVisible(false);
        
        //toDo
        //add PanelAdmitValueInput to panel and to modelsPanels
    }//GEN-LAST:event_jButtonAnalysisActionPerformed

    private void jButtonCreateModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateModelActionPerformed
        jPanelNewDecision.setVisible(false);
        jPanelModels.setVisible(false);
        jPanelCreateCustom.setVisible(true);
        jPanelProvideV.setVisible(false);
        jPanelResults.setVisible(false);
    }//GEN-LAST:event_jButtonCreateModelActionPerformed

    private void jButtonAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalyzeActionPerformed
        jPanelNewDecision.setVisible(false);
        jPanelModels.setVisible(false);
        jPanelCreateCustom.setVisible(false);
        jPanelProvideV.setVisible(false);
        jPanelResults.setVisible(true);
    }//GEN-LAST:event_jButtonAnalyzeActionPerformed

    private void jButtonCustomParamAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomParamAddActionPerformed
        String var= jTextFieldVar.getText().replaceAll(" ", "_");
        if(jTextArea1.getText().equals(""))
            jTextArea1.setText(var);
        else
            jTextArea1.setText(jTextArea1.getText() +" "+ var);
    }//GEN-LAST:event_jButtonCustomParamAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        String eq= jTextArea1.getText();
        String[] list= jTextArea1.getText().split(" ");
        jTextArea1.setText((replaceLast(eq, list[list.length-1], "")).trim());
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCustomSymbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomSymbAddActionPerformed
        String sym= jComboBoxSymbol.getSelectedItem().toString();
        jTextArea1.setText(jTextArea1.getText() +" "+ sym);
    }//GEN-LAST:event_jButtonCustomSymbAddActionPerformed

    /**
     * replace the last substring occurrence
     * @param string the whole string
     * @param toReplace the substring to replace
     * @param replacement with what to replace
     * @return 
     */
    public String replaceLast(String string, String toReplace, String replacement) {
        int pos = string.lastIndexOf(toReplace);
        if (pos > -1) {
            return string.substring(0, pos)
                 + replacement
                 + string.substring(pos + toReplace.length());
        } else {
            return string;
        }
    }
    
    /**
     * Remove all the row data of the table
     * @param table 
     */
    private void removeAllRowsTable(javax.swing.JTable table){
        DefaultTableModel dm = (DefaultTableModel) table.getModel();
        for(int i = dm.getRowCount() - 1; i>=0; i--){
            dm.removeRow(i);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBenefit;
    private javax.swing.JButton jButtonAddCost;
    private javax.swing.JButton jButtonAnalysis;
    private javax.swing.JButton jButtonAnalyze;
    private javax.swing.JButton jButtonCreateCustomModel;
    private javax.swing.JButton jButtonCreateDecision;
    private javax.swing.JButton jButtonCreateModel;
    private javax.swing.JButton jButtonCustomParamAdd;
    private javax.swing.JButton jButtonCustomSymbAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNewDecision;
    private javax.swing.JButton jButtonTune;
    private javax.swing.JComboBox<String> jComboBoxCustomEquation;
    private javax.swing.JComboBox<String> jComboBoxCustomType;
    private javax.swing.JComboBox<String> jComboBoxParameters;
    private javax.swing.JComboBox<String> jComboBoxSymbol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProfitLoss;
    private javax.swing.JLabel jLabelTotalBenefits;
    private javax.swing.JLabel jLabelTotalCosts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCreateCustom;
    private javax.swing.JPanel jPanelModels;
    private javax.swing.JPanel jPanelModelsInputs;
    private javax.swing.JPanel jPanelNewDecision;
    private javax.swing.JPanel jPanelProvideV;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTableAllModels;
    private javax.swing.JTable jTableDecisions;
    private javax.swing.JTable jTableModels;
    private javax.swing.JTable jTableResultBenefitModel;
    private javax.swing.JTable jTableResultCostModel;
    private javax.swing.JTable jTableTotalBC;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextDate;
    private javax.swing.JTextField jTextFieldCustomName;
    private javax.swing.JTextField jTextFieldMaxV;
    private javax.swing.JTextField jTextFieldMinV;
    private javax.swing.JTextField jTextFieldVar;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextOwner;
    // End of variables declaration//GEN-END:variables
}
